name: CI
on:
  push:
    branches:
      - main

jobs:
  behave-tests:
    name: 'Behave Tests'
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
        cache: 'pip'

    - name: Install Dependencies
      run: pip install -r requirements.txt
      
    - name: Run Behave
      run: behave

